import { Briefcase, Users, BarChart3, UserRound } from 'lucide-react';
export const careersPosition = [
  {
    title: 'Business Development Intern',
    slug: 'business-development-intern',
    location: 'Hyderabad',
    experience: 'Fresher',
    background: "https://res.cloudinary.com/denikmblr/image/upload/v1758101904/Frame_1_ompobd.png",
    aboutRole: ` We are looking for a dynamic and target-driven Sales Executive to join our team. In this role, you will be responsible for driving sales, building relationships with clients, and meeting sales targets.
  `,
    icon: Briefcase,
    description: 'Connect with clients and drive business growth',
    skills: ['Leadership', 'Communication', 'Strategy'],
    whatYouDo: [
      `Identify new sales opportunities and generate leads.`,
      `Engage with prospective customers and close sales.`,
      `Maintain and grow relationships with existing clients.`,
      `Achieve sales targets and contribute to revenue growth.`,
      `Prepare and deliver presentations to potential clients.`,
      `Stay updated on product offerings and market trends`,
    ],
    whatWeNeed: [
      `Excellent communication and negotiation skills.`,
      `Strong persuasion and closing abilities.`,
      `Ability to work independently and as part of a team.`,
      `Basic understanding of sales principles and customer needs.`,
      `Self-motivated and results-oriented`,
    ],
    qualifiction: [
      `Bachelor’s degree or equivalent (preferred).`,
      `Previous sales experience is a plus, but not required.`,
    ],
  },
  {
    title: 'HR Intern',
    slug: 'hr-intern',
    location: 'Hyderabad',
    experience: 'Fresher',
    background: "https://res.cloudinary.com/denikmblr/image/upload/v1758105708/Frame_3_1_jjc89h.png",
    aboutRole: `We are seeking a motivated HR Executive to join our team. This entry-level role will support recruitment, employee engagement, and HR administration.
  `,
    icon: Users,
    description: 'Shape our culture and develop our talent',
    skills: ['Culture', 'Recruitment', 'Development'],
    whatYouDo: [
      `Assist in the recruitment process, including posting job ads and scheduling interviews.`,
      `Maintain employee records and handle documentation.`,
      `Help in onboarding new hires and ensuring smooth induction.`,
      `Assist in organizing employee engagement activities.`,
      `Support HR team in day-to-day administrative tasks.`,
    ],
    whatWeNeed: [
      `Strong communication and interpersonal skills.`,
      `Basic knowledge of HR processes.`,
      `Proficient in MS Office and basic HR software.`,
      `Quick learner with a passion for HR`,
    ],
    qualifiction: [
      `Bachelor’s degree in HR, Business Administration, or related field.`,
      `Freshers are welcome to apply`,
    ],
  },
  {
    title: 'Digital Marketing Specialist',
    slug: 'digital-marketing-specialist',
    icon: BarChart3,
    location: 'Hyderabad',
    experience: '2+ years',
    background: "https://res.cloudinary.com/denikmblr/image/upload/v1758105713/Frame_4_t0z9yp.png",

    aboutRole: `We're looking for a Digital Marketing Specialist to join our growing team. You'll be responsible for developing and executing innovative marketing strategies that drive growth and engagement across our digital platforms.
              `,
    description: 'Drive growth through innovative digital strategies',
    skills: ['SEO', 'Content', 'Analytics'],
    whatYouDo: [
      'Plan, implement, and manage digital marketing campaigns across platforms such as social media, email, SEO, and paid search.',
      'Create and manage engaging content for social media, blogs, and websites.',
      `Monitor and report on key performance metrics (Google Analytics, social media insights, etc.).`,
      `Manage social media accounts and develop strategies to increase engagement and followers.`,
      `Implement SEO strategies to enhance search rankings and drive organic traffic.`,
    ],
    whatWeNeed: [
      'Strong proficiency in SEO, SEM, social media marketing, and email campaign',
      `Experience with digital marketing tools like Google Analytics, Google Ads, and social media platforms.`,
      `Excellent written and verbal communication skills.`,
      `Strong analytical and problem-solving skills.`,
      `Ability to work in a fast-paced environment and manage multiple projects`,
    ],
    qualifiction: [
      `Bachelor’s degree in Marketing, Communications, or a related field is preferred.`,
      `At least 2 years of experience in digital marketing.`,
    ],
    other: `Stay current on digital marketing trends, tools, and techniques to ensure effective strategies.`,
  },
  {
    title: 'Mentor',
    slug: 'Mentor',
    location: 'Hyderabad',
    icon: UserRound,
    experience: '5+ years',
    background: "https://res.cloudinary.com/denikmblr/image/upload/v1758107302/Frame_5_j9rtym.png",
    description: 'Optimize processes and drive efficiency',
    skills: ['Process', 'Leadership', 'Innovation'],
    aboutRole: `We are seeking a skilled and passionate instructor with at least 5 years of experience to join our team. The ideal candidate will have a proven track record of delivering high-quality education, engaging students, and helping them achieve their learning goals.`,
    whatYouDo: [
      `Design and deliver program content that meets educational objectives.`,
      `Engage students through interactive teaching methods and activities.`,
      `Assess student progress and provide constructive feedback.`,
      `Mentor and guide students, ensuring a positive and effective learning environment.`,
      `Continuously improve teaching techniques and program materials.`,
      `Stay updated on industry trends and incorporate relevant knowledge into lessons.`,
      `Maintain student records and track academic progress.`,
    ],
    whatWeNeed: [
      `Strong teaching and presentation skills.`,
      `Ability to manage a online classroom and engage students effectively.`,
      ` Expertise in the subject matter.`,
      `Excellent communication, interpersonal, and organizational skills.`,
      `Ability to adapt to different learning styles`,
    ],
    qualifiction: [
      `At least 5 years of teaching experience in the relevant field.`,
      `Bachelor’s degree or higher in the subject area (Master’s preferred).`,
    ],
  },
];
