export interface Course {
  id: number;
  title: string;
  slug?: string;
  price: number;
  image: string;
  topic: string;
  reviews: number;
  rating: number;
  href?: string;
  description: string;
  subtopic: string;
}

export const courseAPIData = [
    {
    id: 5,
    title: 'QA Testing and Automation',
    slug: 'qa-testing-and-automation-c5',
    price: 149.99,
    image: '/images/btech/cse/QAT.png',
    program: 'B.Tech',
    branch: 'Computer Science Engineering',
    priority: 5,
    reviews: 9,
    rating: 5,
    description:
      'Learn how to perform manual and automated testing to ensure software quality.',
    subtopic: 'Automation and Manual Testing',
    topic: 'Engineering',
  },

    {
    id: 4,
    title: 'Full Stack web Development',
    slug: 'full-stack-web-development-c4',
    price: 89.99,
    image: '/images/vision/fullstack.webp',
    program: 'B.Tech',
    branch: 'Computer Science Engineering',
    priority: 4,
    reviews: 6,
    rating: 4,
    description:
      'Comprehensive training in building both front-end and back-end of web applications.',
    subtopic: 'Front-end and Back-end Development',
  },
    {
    id: 3,
    title: 'Artificial Intelligence & Machine Learning',
    slug: 'artificial-intelligence-c1',
    price: 150.0,
    image: '/images/vision/artificial-intelligence.webp',
    program: 'B.Tech',
    branch: 'Computer Science Engineering',
    priority: 1,
    reviews: 15,
    rating: 4,
    description:
      'An introduction to AI and ML concepts, algorithms, and applications in various industries.',
    subtopic: 'Machine Learning and Neural Networks',
  },
  
  {
    id: 201,
    title: 'Clinical Data management',
    slug: 'clinical-data-management-c3',
    price: 180.0,
    image: '/images/vision/clinicaldatamanagement.png',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 6,
    reviews: 12,
    rating: 5,
    description:
      'Learn techniques to extract insights from clinical datasets for evidence-based decisions in healthcare and pharma.',
    subtopic: 'Clinical datasets, EDA, statistics, and reporting',
  },
  {
    id: 202,
    title: 'Pharma Quality Assurance',
    slug: 'pharma-quality-assurance-c2',
    price: 170.0,
    image: '/images/pharmacy/drug.webp',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 6,
    reviews: 10,
    rating: 4,
    description:
      'Master QA concepts for pharma including cGMP, validation, documentation, audits, and compliance.',
    subtopic: 'cGMP, validation, CAPA, audits',
  },
  {
    id: 203,
    title: 'Medical Writing',
    slug: 'medical-writing-c1',
    price: 160.0,
    image: '/images/vision/clinical-trial-research.webp',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 6,
    reviews: 11,
    rating: 4,
    description:
      'Develop regulatory and scientific writing skills for protocols, CSRs, manuscripts, and publication ethics.',
    subtopic: 'Regulatory documents and publication standards',
  },
  {
    id: 204,
    title: 'Clinical SAAS',
    slug: 'Clinical-SAS-c31',
    price: 170.0,
    image: '/images/vision/clinical-trial-research.webp',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 6,
    reviews: 12,
    rating: 5,
    description:
      'Learn SAS for clinical trials: data management, analysis, TLFs, and regulatory reporting.',
    subtopic: 'TLFs, SDTM/ADaM, CDISC, FDA submissions',
  },
  {
    id: 205,
    title: 'Clinical Research',
    slug: 'clinical-research-c205',
    price: 180.0,
    image: '/images/vision/clincalresearch.png',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 6,
    reviews: 10,
    rating: 4,
    description:
      'End-to-end clinical research processes: ICH-GCP, trial design, ethics, monitoring, documentation.',
    subtopic: 'ICH-GCP, protocol, CRF, monitoring, SAE',
  },
  {
    id: 206,
    title: 'Clinical Research Coordinator',
    slug: 'clinical-research-coordinator-c206',
    price: 170.0,
    image: '/images/vision/clinicalreseachco.png',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 6,
    reviews: 9,
    rating: 4,
    description:
      'Practical CRC responsibilities: site management, patient recruitment, documentation, and regulatory coordination.',
    subtopic: 'Site coordination, consenting, logs, SDV, audits',
  },
  // Replicate required pharma/degree variants for the nine spotlight courses across all 6 programs
  // Clinical Data management
  { id: 207, title: 'Clinical Data management', slug: 'clinical-data-management-c3', price: 180.0, image: '/images/vision/clinicaldatamanagement.png', program: 'Pharmacy', branch: 'Master of Pharmacy', priority: 6, reviews: 12, rating: 5, description: 'Insights from clinical datasets for pharma decisions.', subtopic: 'EDA, stats, reporting' },
  { id: 208, title: 'Clinical Data management', slug: 'clinical-data-management-c3', price: 180.0, image: '/images/vision/clinicaldatamanagement.png', program: 'Pharmacy', branch: 'Doctor of Pharmacy', priority: 6, reviews: 12, rating: 5, description: 'Insights from clinical datasets for pharma decisions.', subtopic: 'EDA, stats, reporting' },
  { id: 209, title: 'Clinical Data management', slug: 'clinical-data-management-c3', price: 180.0, image: '/images/vision/clinicaldatamanagement.png', program: 'Pharmacy', branch: 'Diploma in Pharmacy', priority: 6, reviews: 12, rating: 5, description: 'Insights from clinical datasets for pharma decisions.', subtopic: 'EDA, stats, reporting' },
  { id: 210, title: 'Clinical Data management', slug: 'clinical-data-management-c3', price: 180.0, image: '/images/vision/clinicaldatamanagement.png', program: 'Degree', branch: 'Master of Science', priority: 6, reviews: 12, rating: 5, description: 'Insights from clinical datasets for healthcare/pharma.', subtopic: 'EDA, stats, reporting' },
  // Pharma Quality Assurance
  { id: 211, title: 'Pharma Quality Assurance', slug: 'pharma-quality-assurance-c2', price: 170.0, image: '/images/pharmacy/drug.webp', program: 'Pharmacy', branch: 'Master of Pharmacy', priority: 6, reviews: 10, rating: 4, description: 'QA in pharma: cGMP, validation, audits, compliance.', subtopic: 'cGMP, validation, CAPA, audits' },
  { id: 212, title: 'Pharma Quality Assurance', slug: 'pharma-quality-assurance-c2', price: 170.0, image: '/images/pharmacy/drug.webp', program: 'Pharmacy', branch: 'Doctor of Pharmacy', priority: 6, reviews: 10, rating: 4, description: 'QA in pharma: cGMP, validation, audits, compliance.', subtopic: 'cGMP, validation, CAPA, audits' },
  { id: 213, title: 'Pharma Quality Assurance', slug: 'pharma-quality-assurance-c2', price: 170.0, image: '/images/pharmacy/drug.webp', program: 'Pharmacy', branch: 'Diploma in Pharmacy', priority: 6, reviews: 10, rating: 4, description: 'QA in pharma: cGMP, validation, audits, compliance.', subtopic: 'cGMP, validation, CAPA, audits' },
  { id: 214, title: 'Pharma Quality Assurance', slug: 'pharma-quality-assurance-c2', price: 170.0, image: '/images/pharmacy/drug.webp', program: 'Degree', branch: 'Master of Science', priority: 6, reviews: 10, rating: 4, description: 'QA and compliance in pharma manufacturing.', subtopic: 'cGMP, validation, CAPA, audits' },
  // Medical Writing
  { id: 215, title: 'Medical Writing', slug: 'medical-writing-c1', price: 160.0, image: '/images/vision/clinical-trial-research.webp', program: 'Pharmacy', branch: 'Master of Pharmacy', priority: 6, reviews: 11, rating: 4, description: 'Regulatory/scientific writing: protocols, CSRs, manuscripts.', subtopic: 'Regulatory docs and publication standards' },
  { id: 216, title: 'Medical Writing', slug: 'medical-writing-c1', price: 160.0, image: '/images/vision/clinical-trial-research.webp', program: 'Pharmacy', branch: 'Doctor of Pharmacy', priority: 6, reviews: 11, rating: 4, description: 'Regulatory/scientific writing: protocols, CSRs, manuscripts.', subtopic: 'Regulatory docs and publication standards' },
  { id: 217, title: 'Medical Writing', slug: 'medical-writing-c1', price: 160.0, image: '/images/vision/clinical-trial-research.webp', program: 'Pharmacy', branch: 'Diploma in Pharmacy', priority: 6, reviews: 11, rating: 4, description: 'Regulatory/scientific writing: protocols, CSRs, manuscripts.', subtopic: 'Regulatory docs and publication standards' },
  { id: 218, title: 'Medical Writing', slug: 'medical-writing-c1', price: 160.0, image: '/images/vision/clinical-trial-research.webp', program: 'Degree', branch: 'Master of Science', priority: 6, reviews: 11, rating: 4, description: 'Regulatory/scientific writing for clinical docs.', subtopic: 'Regulatory docs and publication standards' },
  // Clinical SAAS (SAS)
  { id: 219, title: 'Clinical SAS', slug: 'Clinical-SAS-c31', price: 170.0, image: '/images/vision/clinical-trial-research.webp', program: 'Pharmacy', branch: 'Master of Pharmacy', priority: 6, reviews: 12, rating: 5, description: 'SAS for clinical trials: data, TLFs, submissions.', subtopic: 'TLFs, SDTM/ADaM, CDISC' },
  { id: 220, title: 'Clinical SAS', slug: 'Clinical-SAS-c31', price: 170.0, image: '/images/vision/clinical-trial-research.webp', program: 'Pharmacy', branch: 'Doctor of Pharmacy', priority: 6, reviews: 12, rating: 5, description: 'SAS for clinical trials: data, TLFs, submissions.', subtopic: 'TLFs, SDTM/ADaM, CDISC' },
  { id: 221, title: 'Clinical SAS', slug: 'Clinical-SAS-c31', price: 170.0, image: '/images/vision/clinical-trial-research.webp', program: 'Pharmacy', branch: 'Diploma in Pharmacy', priority: 6, reviews: 12, rating: 5, description: 'SAS for clinical trials: data, TLFs, submissions.', subtopic: 'TLFs, SDTM/ADaM, CDISC' },
  { id: 222, title: 'Clinical SAS', slug: 'Clinical-SAS-c31', price: 170.0, image: '/images/vision/clinical-trial-research.webp', program: 'Degree', branch: 'Master of Science', priority: 6, reviews: 12, rating: 5, description: 'SAS applied to clinical data for analysis/reporting.', subtopic: 'TLFs, SDTM/ADaM, CDISC' },
  // Clinical Research
  { id: 223, title: 'Clinical Research', slug: 'clinical-research-c205', price: 180.0, image: '/images/vision/clincalresearch.png', program: 'Pharmacy', branch: 'Master of Pharmacy', priority: 6, reviews: 10, rating: 4, description: 'Clinical trials: GCP, protocols, monitoring, ethics.', subtopic: 'ICH-GCP, protocol, CRF, SAE' },
  { id: 224, title: 'Clinical Research', slug: 'clinical-research-c205', price: 180.0, image: '/images/vision/clincalresearch.png', program: 'Pharmacy', branch: 'Doctor of Pharmacy', priority: 6, reviews: 10, rating: 4, description: 'Clinical trials: GCP, protocols, monitoring, ethics.', subtopic: 'ICH-GCP, protocol, CRF, SAE' },
  { id: 225, title: 'Clinical Research', slug: 'clinical-research-c205', price: 180.0, image: '/images/vision/clincalresearch.png', program: 'Pharmacy', branch: 'Diploma in Pharmacy', priority: 6, reviews: 10, rating: 4, description: 'Clinical trials: GCP, protocols, monitoring, ethics.', subtopic: 'ICH-GCP, protocol, CRF, SAE' },
  { id: 226, title: 'Clinical Research', slug: 'clinical-research-c205', price: 180.0, image: '/images/vision/clincalresearch.png', program: 'Degree', branch: 'Master of Science', priority: 6, reviews: 10, rating: 4, description: 'Clinical research fundamentals for life sciences.', subtopic: 'ICH-GCP, protocol, CRF, SAE' },
  // Clinical Research Coordinator
  { id: 227, title: 'Clinical Research Coordinator', slug: 'clinical-research-coordinator-c206', price: 170.0, image: '/images/vision/clinicalreseachco.png', program: 'Pharmacy', branch: 'Master of Pharmacy', priority: 6, reviews: 9, rating: 4, description: 'CRC role: site coordination, documentation, audits.', subtopic: 'Site coordination, consenting, logs, SDV, audits' },
  { id: 228, title: 'Clinical Research Coordinator', slug: 'clinical-research-coordinator-c206', price: 170.0, image: '/images/vision/clinicalreseachco.png', program: 'Pharmacy', branch: 'Doctor of Pharmacy', priority: 6, reviews: 9, rating: 4, description: 'CRC role: site coordination, documentation, audits.', subtopic: 'Site coordination, consenting, logs, SDV, audits' },
  { id: 229, title: 'Clinical Research Coordinator', slug: 'clinical-research-coordinator-c206', price: 170.0, image: '/images/vision/clinicalreseachco.png', program: 'Pharmacy', branch: 'Diploma in Pharmacy', priority: 6, reviews: 9, rating: 4, description: 'CRC role: site coordination, documentation, audits.', subtopic: 'Site coordination, consenting, logs, SDV, audits' },
  { id: 230, title: 'Clinical Research Coordinator', slug: 'clinical-research-coordinator-c206', price: 170.0, image: '/images/vision/clinicalreseachco.png', program: 'Degree', branch: 'Master of Science', priority: 6, reviews: 9, rating: 4, description: 'CRC responsibilities in clinical settings.', subtopic: 'Site coordination, consenting, logs, SDV, audits' },
  // AI in Pharmaceuticals
  { id: 231, title: 'Artificial Intelligence in Pharmaceuticals', slug: 'Artificial-Intelligence-c32', price: 170.0, image: '/images/pharmacy/ai.webp', program: 'Pharmacy', branch: 'Doctor of Pharmacy', priority: 6, reviews: 16, rating: 4, description: 'AI transforming drug discovery, trials, personalization.', subtopic: 'AI in Drug Discovery and Development' },
  { id: 232, title: 'Artificial Intelligence in Pharmaceuticals', slug: 'Artificial-Intelligence-c32', price: 170.0, image: '/images/pharmacy/ai.webp', program: 'Pharmacy', branch: 'Diploma in Pharmacy', priority: 6, reviews: 16, rating: 4, description: 'AI transforming drug discovery, trials, personalization.', subtopic: 'AI in Drug Discovery and Development' },
  { id: 233, title: 'Artificial Intelligence in Pharmaceuticals', slug: 'Artificial-Intelligence-c32', price: 170.0, image: '/images/pharmacy/ai.webp', program: 'Degree', branch: 'Bachelor of Science', priority: 6, reviews: 16, rating: 4, description: 'AI for healthcare and pharmaceutical domains.', subtopic: 'AI in Drug Discovery and Development' },
  { id: 234, title: 'Artificial Intelligence in Pharmaceuticals', slug: 'Artificial-Intelligence-c32', price: 170.0, image: '/images/pharmacy/ai.webp', program: 'Degree', branch: 'Master of Science', priority: 6, reviews: 16, rating: 4, description: 'AI for healthcare and pharmaceutical domains.', subtopic: 'AI in Drug Discovery and Development' },
  {
    id: 1,
    title: 'Data Science ',
    slug: 'data-science-and-analytics-c3',
    price: 199.99,
    image: '/images/btech/cse/ds.avif',
    program: 'B.Tech',
    branch: 'Computer Science Engineering',
    priority: 3,
    reviews: 12,
    rating: 4,
    description:
      'Explore data analysis techniques, data visualization, and the use of data science tools for insights.',
    subtopic: 'Data Visualization and Predictive Analytics',
  },
    {
    id: 13,
    title: 'Medical Coding',
    slug: 'Medical-Coding-c13',
    price: 120.0,
    image: '/images/vision/med-coding.webp',
    program: 'B.Tech',
    branch: 'Biotechnology Engineering',
    priority: 1,
    reviews: 8,
    rating: 4,
    description:
      'Learn how to translate healthcare diagnoses, procedures, and medical services into codes.',
    subtopic: 'Healthcare and Billing Codes',
  },
    {
    id: 28,
    title: ' Clinical SAS Programming',
    slug: 'SAS-Programming-c28',
    price: 150.0,
    image: '/images/vision/sas-programming.webp',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 2,
    reviews: 12,
    rating: 5,
    description:
      'Master the SAS software for data analysis, statistical modeling, and report generation in the pharmaceutical industry.',
    subtopic: 'Data Analysis and Statistical Modeling',
  },
    {
    id: 16,
    title: 'Nano Science and Nano Technology',
    slug: 'Nano-Science-Nano-Technology-c16',
    price: 180.0,
    image: '/images/btech/biotech/nano.webp',
    program: 'B.Tech',
    branch: 'Biotechnology Engineering',
    priority: 4,
    reviews: 14,
    rating: 4,
    description:
      'Explore the principles of nanotechnology and its application in various fields like medicine, electronics, and energy.',
    subtopic: 'Nanomaterials and Nanomedicine',
  },
  {
    id: 30,
    title: 'Nano Science and Nano Technology',
    slug: 'Nano-Science-and-Nano-Technology-c30',
    price: 180.0,
    image: '/images/pharmacy/nano.webp',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 4,
    reviews: 14,
    rating: 4,
    description:
      'Explore the field of nanotechnology, including its applications in drug delivery, diagnostics, and medical devices.',
    subtopic: 'Nanomedicine and Drug Delivery Systems',
  },
    {
    id: 15,
    title: 'Pharmacovigilance and Clinical Research',
    slug: 'Pharmacovigilance-c15',
    price: 140.0,
    image: '/images/pharmacy/drug.webp',
    program: 'B.Tech',
    branch: 'Biotechnology Engineering',
    priority: 3,
    reviews: 9,
    rating: 4,
    description:
      'Understand the science and activities related to the detection, assessment, and prevention of adverse effects in medicines.',
    subtopic: 'Drug Safety and Risk Management',
  },
  

  // {
  //   id: 2,
  //   title: 'Machine Learning',
  //   slug: 'machine-learning-c2',
  //   price: 129.99,
  //   image: '/images/vision/machine-learning.jpg',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 2,
  //   reviews: 8,
  //   rating: 5,
  //   description:
  //     'Learn the fundamentals of machine learning, including algorithms, models, and data preparation.',
  //   subtopic: 'Supervised and Unsupervised Learning',
  // },
 


  // {
  //   id: 6,
  //   title: 'Power BI',
  //   slug: 'power-bi-for-data-visualization-c6',
  //   price: 120.0,
  //   image: '/images/vision/powerbi.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 6,
  //   reviews: 10,
  //   rating: 4,
  //   description:
  //     'Master Power BI for creating compelling, interactive data visualizations and reports.',
  //   subtopic: 'Business Intelligence and Data Visualization',
  // },
  // {
  //   id: 7,
  //   title: 'DevOps',
  //   slug: 'devops-c7',
  //   price: 179.99,
  //   image: '/images/vision/devops.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 7,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Learn the principles of DevOps for continuous integration, delivery, and automation.',
  //   subtopic: 'CI/CD and Infrastructure Automation',
  // },
  // {
  //   id: 8,
  //   title: 'Cloud Computing',
  //   slug: 'cloud-computing-c8',
  //   price: 140.0,
  //   image: '/images/vision/cloud-computing.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 8,
  //   reviews: 7,
  //   rating: 5,
  //   description:
  //     'Understand the fundamentals of cloud computing and services offered by AWS, Azure, and Google Cloud.',
  //   subtopic: 'Cloud Infrastructure and Services',
  // },
  // {
  //   id: 9,
  //   title: 'Cyber security ',
  //   slug: 'cybersecurity-and-ethical-hacking-c9',
  //   price: 159.99,
  //   image: '/images/btech/cse/cyber.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 9,
  //   reviews: 9,
  //   rating: 4,
  //   description:
  //     'Learn the core concepts of cybersecurity and ethical hacking to protect systems from threats.',
  //   subtopic: 'Network Security and Ethical Hacking',
  // },
  // {
  //   id: 10,
  //   title: 'Mobile App Development',
  //   slug: 'mobile-app-development-c10',
  //   price: 139.99,
  //   image: '/images/vision/mobile-development.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 10,
  //   reviews: 13,
  //   rating: 5,
  //   description:
  //     'A course covering both Android and iOS mobile app development from basics to advanced techniques.',
  //   subtopic: 'Mobile Development Frameworks and Platforms',
  // },
  // {
  //   id: 11,
  //   title: 'Robotics',
  //   slug: 'robotics-c11',
  //   price: 149.99,
  //   image: '/images/vision/robotics.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 11,
  //   reviews: 10,
  //   rating: 4,
  //   description:
  //     'An introduction to robotics, including hardware, programming, and automation systems.',
  //   subtopic: 'Robotics Engineering and Automation',
  // },
  // {
  //   id: 12,
  //   title: 'AR/VR Development',
  //   slug: 'augmented-reality-and-virtual-reality-c12',
  //   price: 180.0,
  //   image: '/images/vision/augemented.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 12,
  //   reviews: 11,
  //   rating: 4,
  //   description:
  //     'Learn how to design and develop interactive AR and VR applications for immersive experiences.',
  //   subtopic: 'Interactive Simulations and Immersive Design',
  // },
  // {
  //   id: 12,
  //   title: 'Medical Coding',
  //   slug: 'Medical-Coding-c13',
  //   price: 120.0,
  //   image: '/images/vision/med-coding.webp',
  //   program: 'B.Tech',
  //   branch: 'Computer Science Engineering',
  //   priority: 12,
  //   reviews: 8,
  //   rating: 4,
  //   description:
  //     'Learn how to translate healthcare diagnoses, procedures, and medical services into codes.',
  //   subtopic: 'Healthcare and Billing Codes',
  // },

  // Biotechnology-Engineering

  {
    id: 14,
    title: 'Clinical SAS Programming',
    slug: 'SAS-Programming-c14',
    price: 150.0,
    image: '/images/vision/sas-programming.webp',
    program: 'B.Tech',
    branch: 'Biotechnology Engineering',
    priority: 2,
    reviews: 12,
    rating: 5,
    description:
      'Master the SAS software used for advanced analytics, statistical modeling, and data management.',
    subtopic: 'Data Analytics and Statistical Modeling',
  },


  // {
  //   id: 17,
  //   title: 'Artificial Intelligence & Machine Learning',
  //   slug: 'Artificial-Intelligence-c17',
  //   price: 160.0,
  //   image: '/images/vision/artificial-intelligence.webp',
  //   program: 'B.Tech',
  //   branch: 'Biotechnology Engineering',
  //   priority: 5,
  //   reviews: 13,
  //   rating: 5,
  //   description:
  //     'Learn how AI is revolutionizing healthcare through diagnostic systems, predictive analysis, and personalized medicine.',
  //   subtopic: 'Machine Learning and Healthcare Applications',
  // },
  // {
  //   id: 18,
  //   title: 'Regulatory Affairs',
  //   slug: 'Regulatory-Affairs-c18',
  //   price: 150.0,
  //   image: '/images/vision/regulatory-affairs.webp',
  //   program: 'B.Tech',
  //   branch: 'Biotechnology Engineering',
  //   priority: 6,
  //   reviews: 10,
  //   rating: 4,
  //   description:
  //     'Study the regulations and guidelines governing the approval and marketing of pharmaceutical and medical products.',
  //   subtopic: 'Regulation and Compliance',
  // },
  // {
  //   id: 19,
  //   title: 'Bioinformatics',
  //   slug: 'Bioinformatics-c19',
  //   price: 170.0,
  //   image: '/images/vision/bio-informatics.webp',
  //   program: 'B.Tech',
  //   branch: 'Biotechnology Engineering',
  //   priority: 7,
  //   reviews: 11,
  //   rating: 5,
  //   description:
  //     'Learn how to analyze biological data using computational tools, focusing on genomics and molecular biology.',
  //   subtopic: 'Genomics and Computational Biology',
  // },
  // {
  //   id: 20,
  //   title: 'Molecular Biology and Genetics',
  //   slug: 'Molecular-Biology-Genetics-c20',
  //   price: 140.0,
  //   image: '/images/btech/biotech/molecular.avif',
  //   program: 'B.Tech',
  //   branch: 'Biotechnology Engineering',
  //   priority: 8,
  //   reviews: 9,
  //   rating: 4,
  //   description:
  //     'Understand the molecular basis of genetic inheritance, DNA/RNA analysis, and gene expression.',
  //   subtopic: 'Genetic Engineering and Molecular Genetics',
  // },

  // Civil Engineering
  // {
  //   id: 21,
  //   title: 'AutoCAD',
  //   slug: 'AutoCAD-c21',
  //   price: 130.0,
  //   image: '/images/btech/mechanical/autocad.webp',
  //   program: 'B.Tech',
  //   branch: 'Civil Engineering',
  //   priority: 1,
  //   reviews: 15,
  //   rating: 4,
  //   description:
  //     'Learn the fundamentals of AutoCAD to create 2D and 3D drawings for engineering and design purposes.',
  //   subtopic: 'Drafting and 3D Modeling',
  // },
  // {
  //   id: 22,
  //   title: 'Construction Management',
  //   slug: 'Construction-Management-c22',
  //   price: 160.0,
  //   image: '/images/vision/construction-planning.webp',
  //   program: 'B.Tech',
  //   branch: 'Civil Engineering',
  //   priority: 2,
  //   reviews: 12,
  //   rating: 5,
  //   description:
  //     'Study key concepts in construction project management, including planning, budgeting, and resource allocation.',
  //   subtopic: 'Project Planning and Resource Management',
  // },

  //Electronics and Communication Engineering
  // {
  //   id: 23,
  //   title: 'Embedded Systems Design',
  //   slug: 'Embedded-Systems-Design-c23',
  //   price: 150.0,
  //   image: '/images/btech/ee/embedded.webp',
  //   program: 'B.Tech',
  //   branch: 'Electronics and Communication Engineering',
  //   priority: 1,
  //   reviews: 14,
  //   rating: 5,
  //   description:
  //     'Learn to design, develop, and implement embedded systems for various applications in industries.',
  //   subtopic: 'Microcontrollers and Real-Time Operating Systems',
  // },
  // {
  //   id: 24,
  //   title: 'Robotics',
  //   slug: 'Robotics-c24',
  //   price: 170.0,
  //   image: '/images/vision/robotics.webp',
  //   program: 'B.Tech',
  //   branch: 'Electronics and Communication Engineering',
  //   priority: 2,
  //   reviews: 16,
  //   rating: 4,
  //   description:
  //     'An introduction to robotics, covering robot design, programming, and automation systems.',
  //   subtopic: 'Robotic Design and Programming',
  // },
  // {
  //   id: 25,
  //   title: 'VLSI Design',
  //   slug: 'VLSI-Design-c25',
  //   price: 180.0,
  //   image: '/images/btech/ece/vlsi.webp',
  //   program: 'B.Tech',
  //   branch: 'Electronics and Communication Engineering',
  //   priority: 3,
  //   reviews: 10,
  //   rating: 5,
  //   description:
  //     'Explore the design, testing, and implementation of very-large-scale integrated (VLSI) circuits.',
  //   subtopic: 'Semiconductor Devices and Circuit Design',
  // },
  // {
  //   id: 26,
  //   title: 'Wireless Networks',
  //   slug: 'Wireless-Networks-c26',
  //   price: 160.0,
  //   image: '/images/btech/ece/wireless.webp',
  //   program: 'B.Tech',
  //   branch: 'Electronics and Communication Engineering',
  //   priority: 4,
  //   reviews: 12,
  //   rating: 4,
  //   description:
  //     'Understand the principles of wireless networks, including protocols, communication systems, and security.',
  //   subtopic: 'Network Protocols and Wireless Security',
  // },

  // bachelor of pharmacy
  {
    id: 27,
    title: 'Medical Coding',
    slug: 'Medical-Coding-c27',
    price: 120.0,
    image: '/images/vision/med-coding.webp',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 1,
    reviews: 15,
    rating: 4,
    description:
      'Learn the process of translating medical diagnoses, procedures, and services into standardized codes.',
    subtopic: 'Healthcare Coding and Billing',
  },

  {
    id: 29,
    title: 'Pharmacovigilance',
    slug: 'Pharmacovigilance-c29',
    price: 140.0,
    image: '/images/pharmacy/drug.webp',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 3,
    reviews: 18,
    rating: 5,
    description:
      'Learn about the science and activities related to the detection, assessment, and prevention of adverse drug reactions.',
    subtopic: 'Drug Safety and Risk Management',
  },
  
  // {
  //   id: 31,
  //   title: 'Clinical Trials and Research ',
  //   slug: 'Clinical-SAS-c31',
  //   price: 160.0,
  //   image: '/images/vision/clinical-trial-research.webp',
  //   program: 'Pharmacy',
  //   branch: 'Bachelor of Pharmacy',
  //   priority: 5,
  //   reviews: 10,
  //   rating: 5,
  //   description:
  //     'Gain expertise in clinical trials and research methodologies, focusing on data collection, analysis, and regulatory compliance.',
  //   subtopic: 'Clinical Data Analysis and Reporting',
  // },
  {
    id: 32,
    title: 'Artificial Intelligence in Pharmaceuticals',
    slug: 'Artificial-Intelligence-c32',
    price: 170.0,
    image: '/images/pharmacy/ai.webp',
    program: 'Pharmacy',
    branch: 'Bachelor of Pharmacy',
    priority: 6,
    reviews: 16,
    rating: 4,
    description:
      'Discover how AI and machine learning are transforming drug development, clinical trials, and personalized medicine.',
    subtopic: 'AI in Drug Discovery and Development',
  },
  // {
  //   id: 33,
  //   title: 'Drug Development Process',
  //   slug: 'Drug-Development-Process-c33',
  //   price: 200.0,
  //   image: '/images/pharmacy/drug.webp',
  //   program: 'Pharmacy',
  //   branch: 'Bachelor of Pharmacy',
  //   priority: 7,
  //   reviews: 12,
  //   rating: 5,
  //   description:
  //     'Study the entire drug development process, from preclinical research to regulatory approval and market launch.',
  //   subtopic: 'Pharmaceutical Development and Regulatory Affairs',
  // },
  // {
  //   id: 34,
  //   title: 'Regulatory Affairs',
  //   slug: 'Regulatory-Affairs-c34',
  //   price: 150.0,
  //   image: '/images/pharmacy/regular.webp',
  //   program: 'Pharmacy',
  //   branch: 'Bachelor of Pharmacy',
  //   priority: 8,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Understand the regulatory framework governing pharmaceutical products, including FDA guidelines and international standards.',
  //   subtopic: 'Regulation and Compliance',
  // },

  //master of pharmacy
  {
    id: 35,
    title: 'Medical Coding',
    slug: 'Medical-Coding-c35',
    price: 120.0,
    image: '/images/vision/med-coding.webp',
    program: 'Pharmacy',
    branch: 'Master of Pharmacy',
    priority: 1,
    reviews: 18,
    rating: 4,
    description:
      'Learn the process of translating medical diagnoses, procedures, and services into standardized codes for insurance and billing purposes.',
    subtopic: 'Healthcare Coding and Billing',
  },
  {
    id: 36,
    title: ' Clinical SAS Programming',
    slug: 'SAS-Programming-c36',
    price: 150.0,
    image: '/images/vision/sas-programming.webp',
    program: 'Pharmacy',
    branch: 'Master of Pharmacy',
    priority: 2,
    reviews: 12,
    rating: 5,
    description:
      'Master  Clinical SAS Programming for advanced data analysis, statistical modeling, and clinical trial reporting in the pharmaceutical industry.',
    subtopic: 'Data Analysis and Clinical Research',
  },
  {
    id: 37,
    title: 'Pharmacovigilance',
    slug: 'Pharmacovigilance-c37',
    price: 140.0,
    image: '/images/pharmacy/drug.webp',
    program: 'Pharmacy',
    branch: 'Master of Pharmacy',
    priority: 3,
    reviews: 14,
    rating: 5,
    description:
      'Study the science of monitoring the safety of pharmaceutical products, focusing on adverse drug reactions and risk management.',
    subtopic: 'Drug Safety and Risk Assessment',
  },
  {
    id: 38,
    title: 'Nano Science and Nano Technology',
    slug: 'Nano-Science-Nano-Technology-c38',
    price: 180.0,
    image: '/images/pharmacy/nano.webp',
    program: 'Pharmacy',
    branch: 'Master of Pharmacy',
    priority: 4,
    reviews: 16,
    rating: 4,
    description:
      'Explore how nanotechnology is applied in the pharmaceutical industry, including drug delivery systems and diagnostic tools.',
    subtopic: 'Nanomedicine and Drug Delivery',
  },
  // {
  //   id: 39,
  //   title: 'Clinical SAS',
  //   slug: 'Clinical-SAS-c39',
  //   price: 160.0,
  //   image: '/images/pharmacy/clinical.webp',
  //   program: 'Pharmacy',
  //   branch: 'Master of Pharmacy',
  //   priority: 6,
  //   reviews: 11,
  //   rating: 5,
  //   description:
  //     'Learn Clinical  Clinical SAS Programming to analyze clinical trial data, generate reports, and ensure compliance with regulatory standards.',
  //   subtopic: 'Clinical Trial Data Management',
  // },
  // {
  //   id: 40,
  //   title: 'Drug Development Process',
  //   slug: 'Drug-Development-Process-c40',
  //   price: 200.0,
  //   image: '/images/pharmacy/drug.webp',
  //   program: 'Pharmacy',
  //   branch: 'Master of Pharmacy',
  //   priority: 7,
  //   reviews: 13,
  //   rating: 5,
  //   description:
  //     'Study the stages of drug development, from discovery to preclinical trials, clinical trials, and regulatory approval.',
  //   subtopic: 'Pharmaceutical Development and Regulatory Affairs',
  // },

  // {
  //   id: 41,
  //   title: 'Clinical Trials and Research',
  //   slug: 'Clinical-Trials-and-Research-c41',
  //   price: 180.0,
  //   image: '/images/vision/clinical-trial-research.webp',
  //   program: 'Pharmacy',
  //   branch: 'Master of Pharmacy',
  //   priority: 5,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Learn the principles and methods of clinical trials, focusing on trial design, data collection, analysis, and ethical guidelines.',
  //   subtopic: 'Clinical Trial Design and Research Methodology',
  // },
  {
    id: 40,
    title: 'Artificial Intelligence & Machine Learning',
    slug: 'Artificial-Intelligence-mc32',
    price: 170.0,
    image: '/images/vision/artificial-intelligence.webp',
    program: 'Pharmacy',
    branch: 'Master of Pharmacy',
    priority: 6,
    reviews: 16,
    rating: 4,
    description:
      'Discover how AI and machine learning are transforming drug development, clinical trials, and personalized medicine.',
    subtopic: 'AI in Drug Discovery and Development',
  },
  // {
  //   id: 42,
  //   title: 'Regulatory Affairs',
  //   slug: 'Regulatory-Affairs-c42',
  //   price: 150.0,
  //   image: '/images/pharmacy/regular.webp',
  //   program: 'Pharmacy',
  //   branch: 'Master of Pharmacy',
  //   priority: 9,
  //   reviews: 10,
  //   rating: 4,
  //   description:
  //     'Gain an understanding of the regulations and standards governing pharmaceutical products, from development to marketing.',
  //   subtopic: 'Regulation and Compliance in Pharma',
  // },
  {
    id: 43,
    title: 'Medical Coding',
    slug: 'Medical-Coding-c43',
    price: 120.0,
    image: '/images/vision/med-coding.webp',
    program: 'Pharmacy',
    branch: 'Doctor of Pharmacy',
    priority: 2,
    reviews: 18,
    rating: 4,
    description:
      'Learn the process of converting medical diagnoses, procedures, and services into standardized codes for billing and insurance.',
    subtopic: 'Healthcare Coding and Billing',
  },
  {
    id: 44,
    title: ' Clinical SAS Programming',
    slug: 'SAS-Programming-c44',
    price: 150.0,
    image: '/images/vision/sas-programming.webp',
    program: 'Pharmacy',
    branch: 'Doctor of Pharmacy',
    priority: 3,
    reviews: 12,
    rating: 5,
    description:
      'Master  Clinical SAS Programming for clinical trial data analysis, statistical modeling, and regulatory reporting in the pharmaceutical industry.',
    subtopic: 'Clinical Data Analysis and Reporting',
  },
  {
    id: 45,
    title: 'Pharmacovigilance',
    slug: 'Pharmacovigilance-c45',
    price: 140.0,
    image: '/images/pharmacy/drug.webp',
    program: 'Pharmacy',
    branch: 'Doctor of Pharmacy',
    priority: 4,
    reviews: 14,
    rating: 5,
    description:
      'Study the science and practice of detecting, assessing, and preventing adverse drug reactions and other drug-related issues.',
    subtopic: 'Drug Safety and Risk Management',
  },
  {
    id: 46,
    title: 'Nano Science and Nano Technology',
    slug: 'Nano-Science-Nano-Technology-c46',
    price: 180.0,
    image: '/images/pharmacy/nano.webp',
    program: 'Pharmacy',
    branch: 'Doctor of Pharmacy',
    priority: 5,
    reviews: 16,
    rating: 4,
    description:
      'Understand the principles and applications of nanotechnology in drug delivery systems, diagnostics, and therapeutics.',
    subtopic: 'Nanomedicine and Drug Delivery',
  },
  // {
  //   id: 47,
  //   title: 'Clinical Trials and Research',
  //   slug: 'Clinical-Trials-and-Research-c47',
  //   price: 180.0,
  //   image: '/images/vision/clinical-trial-research.webp',
  //   program: 'Pharmacy',
  //   branch: 'Doctor of Pharmacy',
  //   priority: 6,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Learn how clinical trials are conducted, focusing on trial design, data collection, ethical considerations, and research methodology.',
  //   subtopic: 'Clinical Trial Design and Research Methodology',
  // },
  // {
  //   id: 48,
  //   title: 'Regulatory Affairs',
  //   slug: 'Regulatory-Affairs-c48',
  //   price: 150.0,
  //   image: '/images/pharmacy/regular.webp',
  //   program: 'Pharmacy',
  //   branch: 'Doctor of Pharmacy',
  //   priority: 7,
  //   reviews: 10,
  //   rating: 4,
  //   description:
  //     'Gain expertise in the regulatory environment of the pharmaceutical industry, including FDA guidelines and international standards.',
  //   subtopic: 'Pharmaceutical Regulations and Compliance',
  // },
  {
    id: 49,
    title: 'Medical Coding',
    slug: 'Medical-Coding-c49',
    price: 120.0,
    image: '/images/vision/med-coding.webp',
    program: 'Pharmacy',
    branch: 'Diploma in Pharmacy',
    priority: 2,
    reviews: 18,
    rating: 4,
    description:
      'Study the process of coding medical diagnoses and procedures for insurance claims and billing purposes.',
    subtopic: 'Healthcare Coding and Billing',
  },
  {
    id: 50,
    title: ' Clinical SAS Programming',
    slug: 'SAS-Programming-c50',
    price: 150.0,
    image: '/images/vision/sas-programming.webp',
    program: 'Pharmacy',
    branch: 'Diploma in Pharmacy',
    priority: 3,
    reviews: 12,
    rating: 5,
    description:
      'Learn  Clinical SAS Programming for data management, statistical analysis, and report generation in the pharmaceutical industry.',
    subtopic: 'Data Analysis and Pharmaceutical Research',
  },
  {
    id: 51,
    title: 'Pharmacovigilance',
    slug: 'Pharmacovigilance-c51',
    price: 140.0,
    image: '/images/pharmacy/drug.webp',
    program: 'Pharmacy',
    branch: 'Diploma in Pharmacy',
    priority: 4,
    reviews: 14,
    rating: 5,
    description:
      'Explore the science of monitoring and assessing the safety of pharmaceutical products, including adverse drug reactions.',
    subtopic: 'Drug Safety and Risk Management',
  },
  {
    id: 52,
    title: 'Nano Science and Nano Technology',
    slug: 'Nano-Science-Nano-Technology-c52',
    price: 180.0,
    image: '/images/pharmacy/nano.webp',
    program: 'Pharmacy',
    branch: 'Diploma in Pharmacy',
    priority: 5,
    reviews: 16,
    rating: 4,
    description:
      'Learn how nanotechnology is applied in pharmaceutical sciences, focusing on drug delivery systems and therapeutic innovations.',
    subtopic: 'Nanomedicine and Drug Delivery',
  },
  // {
  //   id: 53,
  //   title: 'Clinical Trials and Research',
  //   slug: 'Clinical-Trials-and-Research-c53',
  //   price: 180.0,
  //   image: '/images/vision/clinical-trial-research.webp',
  //   program: 'Pharmacy',
  //   branch: 'Diploma in Pharmacy',
  //   priority: 6,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Understand the process of designing, conducting, and analyzing clinical trials to evaluate the safety and efficacy of pharmaceutical products.',
  //   subtopic: 'Clinical Research and Trial Design',
  // },
  // {
  //   id: 54,
  //   title: 'Regulatory Affairs',
  //   slug: 'Regulatory-Affairs-c54',
  //   price: 150.0,
  //   image: '/images/pharmacy/regular.webp',
  //   program: 'Pharmacy',
  //   branch: 'Diploma in Pharmacy',
  //   priority: 7,
  //   reviews: 10,
  //   rating: 4,
  //   description:
  //     'Gain an understanding of pharmaceutical regulations, including drug approvals, clinical trials, and compliance with international standards.',
  //   subtopic: 'Regulation and Compliance in Pharmaceutical Industry',
  // },
  {
    id: 59,
    title: 'QA Testing and Automation',
    slug: 'qa-testing-c59',
    price: 150.0,
    image: '/images/degree/qaa.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 5,
    reviews: 14,
    rating: 4,
    description:
      'Understand the principles of quality assurance and testing, focusing on manual and automated testing techniques.',
    subtopic: 'Software Testing and Quality Assurance',
  },
  {
    id: 58,
    title: 'Full Stack Web Developement',
    slug: 'full-stack-web-development-c58',
    price: 250.0,
    image: '/images/vision/fullstack.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 4,
    reviews: 20,
    rating: 5,
    description:
      'Learn to build dynamic web applications using both front-end and back-end technologies, including HTML, CSS, JavaScript, and Node.js.',
    subtopic: 'Web Development and Programming',
  },
  {
    id: 55,
    title: 'Artificial Intelligence & Machine Learning',
    slug: 'artificial-intelligence-c55',
    price: 180.0,
    image: '/images/vision/artificial-intelligence.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 1,
    reviews: 15,
    rating: 4,
    description:
      'Learn the fundamentals of AI, including machine learning, neural networks, and natural language processing.',
    subtopic: 'Machine Learning and AI Technologies',
  },
  // {
  //   id: 56,
  //   title: 'Machine Learning',
  //   slug: 'machine-learning-c56',
  //   price: 200.0,
  //   image: '/images/vision/machine-learning.jpg',
  //   program: 'Degree',
  //   branch: 'Bachelor of Computer Applications',
  //   priority: 2,
  //   reviews: 18,
  //   rating: 5,
  //   description:
  //     'Explore machine learning techniques, algorithms, and how they can be used for data prediction and decision-making.',
  //   subtopic: 'Machine Learning Algorithms and Techniques',
  // },
  {
    id: 57,
    title: 'Data Science ',
    slug: 'data-science-c57',
    price: 220.0,
    image: '/images/degree/ds.avif',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 3,
    reviews: 12,
    rating: 5,
    description:
      'Dive into data analysis, statistics, and visualization tools to extract meaningful insights from large datasets.',
    subtopic: 'Data Analysis and Visualization',
  },
  
  // {
  //   id: 60,
  //   title: 'Power BI',
  //   slug: 'power-bi-c60',
  //   price: 170.0,
  //   image: '/images/vision/powerbi.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Computer Applications',
  //   priority: 6,
  //   reviews: 16,
  //   rating: 5,
  //   description:
  //     'Learn how to use Power BI for data visualization, reporting, and interactive dashboards to analyze business data.',
  //   subtopic: 'Business Intelligence and Data Visualization',
  // },

  {
    id: 67,
    title: 'Medical Coding',
    slug: 'medical-coding-c67',
    price: 120.0,
    image: '/images/vision/med-coding.webp',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 1,
    reviews: 18,
    rating: 4,
    description:
      'Learn the process of coding medical diagnoses and procedures for insurance claims and billing purposes.',
    subtopic: 'Healthcare Coding and Billing',
  },
  {
    id: 69,
    title: 'Pharmacovigilance',
    slug: 'pharmacovigilance-c69',
    price: 140.0,
    image: '/images/pharmacy/drug.webp',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 3,
    reviews: 14,
    rating: 5,
    description:
      'Explore the science and practice of detecting, assessing, and preventing adverse drug reactions and other drug-related issues.',
    subtopic: 'Drug Safety and Risk Management',
  },
  {
    id: 70,
    title: 'Nano Science and Nano Technology',
    slug: 'nano-science-nano-technology-c70',
    price: 180.0,
    image: '/images/degree/nano.webp',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 4,
    reviews: 16,
    rating: 4,
    description:
      'Understand the principles and applications of nanotechnology in drug delivery systems, diagnostics, and therapeutics.',
    subtopic: 'Nanomedicine and Drug Delivery',
  },
  {
    id: 75,
    title: 'Human Resource ',
    slug: 'human-resource-c75',
    price: 180.0,
    image: '/images/degree/hr.webp',
    program: 'Degree',
    branch: 'Bachelor of Business Administration',
    priority: 1,
    reviews: 18,
    rating: 4,
    description:
      'Study the practices and principles of managing a company’s workforce, including recruitment, employee relations, and performance management.',
    subtopic: 'Employee Management and Development',
  },
  {
    id: 77,
    title: 'Digital Marketing with AI',
    slug: 'digital-marketing-c77',
    price: 200.0,
    image: '/images/degree/digital.webp',
    program: 'Degree',
    branch: 'Bachelor of Business Administration',
    priority: 3,
    reviews: 15,
    rating: 5,
    description:
      'Gain expertise in digital marketing strategies, including SEO, content marketing, social media, and email campaigns.',
    subtopic: 'Digital Marketing Strategies',
  },
  // {
  //   id: 76,
  //   title: 'Finance',
  //   slug: 'finance-c75',
  //   price: 190.0,
  //   image: '/images/degree/finance.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 2,
  //   reviews: 22,
  //   rating: 5,
  //   description:
  //     'Learn the principles of financial management, including investment strategies, accounting, and financial analysis.',
  //   subtopic: 'Financial Management and Analysis',
  // },

  {
    id: 61,
    title: 'DevOps',
    slug: 'devops-c61',
    price: 200.0,
    image: '/images/vision/devops.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 7,
    reviews: 10,
    rating: 5,
    description:
      'Understand the principles of DevOps, focusing on automation, continuous integration, and continuous delivery (CI/CD) pipelines.',
    subtopic: 'Automation and Continuous Integration',
  },
  {
    id: 62,
    title: 'Cloud Computing and Devops',
    slug: 'cloud-computing-c62',
    price: 220.0,
    image: '/images/vision/cloud-computing.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 8,
    reviews: 14,
    rating: 5,
    description:
      'Learn cloud computing concepts and how to implement solutions using popular cloud platforms like AWS, Azure, and Google Cloud.',
    subtopic: 'Cloud Services and Solutions',
  },
  {
    id: 63,
    title: 'Cyber Security',
    slug: 'cyber-security-c63',
    price: 180.0,
    image: '/images/degree/cyber.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 9,
    reviews: 16,
    rating: 4,
    description:
      'Understand the key principles of cyber security, including encryption, risk management, and ethical hacking.',
    subtopic: 'Information Security and Ethical Hacking',
  },
  {
    id: 64,
    title: 'Mobile App Development',
    slug: 'mobile-app-development-c64',
    price: 210.0,
    image: '/images/vision/mobile-development.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 10,
    reviews: 12,
    rating: 5,
    description:
      'Learn how to design and develop mobile applications for iOS and Android using frameworks like Flutter and React Native.',
    subtopic: 'Mobile App Development and Design',
  },
  {
    id: 65,
    title: 'Robotics',
    slug: 'robotics-c65',
    price: 230.0,
    image: '/images/vision/robotics.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 11,
    reviews: 14,
    rating: 5,
    description:
      'Study the fundamentals of robotics, including robot design, programming, and control systems for automation.',
    subtopic: 'Robotics and Automation',
  },
  {
    id: 66,
    title: 'AR/VR Development',
    slug: 'arvr-development-c66',
    price: 250.0,
    image: '/images/vision/augemented.webp',
    program: 'Degree',
    branch: 'Bachelor of Computer Applications',
    priority: 12,
    reviews: 20,
    rating: 5,
    description:
      'Learn how to create immersive augmented and virtual reality experiences using tools like Unity and Unreal Engine.',
    subtopic: 'Augmented and Virtual Reality',
  },
  // {
  //   id: 67,
  //   title: 'Medical Coding',
  //   slug: 'medical-coding-c67',
  //   price: 120.0,
  //   image: '/images/vision/med-coding.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Science',
  //   priority: 1,
  //   reviews: 18,
  //   rating: 4,
  //   description:
  //     'Learn the process of coding medical diagnoses and procedures for insurance claims and billing purposes.',
  //   subtopic: 'Healthcare Coding and Billing',
  // },
  {
    id: 68,
    title: ' Clinical SAS Programming',
    slug: 'sas-programming-c68',
    price: 150.0,
    image: '/images/vision/sas-programming.webp',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 2,
    reviews: 12,
    rating: 5,
    description:
      'Learn  Clinical SAS Programming for clinical trial data analysis, statistical modeling, and regulatory reporting in the pharmaceutical industry.',
    subtopic: 'Clinical Data Analysis and Reporting',
  },

  // {
  //   id: 71,
  //   title: 'Clinical SAS',
  //   slug: 'clinical-sas-c71',
  //   price: 170.0,
  //   image: '/images/degree/clinical.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Science',
  //   priority: 5,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Study the use of SAS in clinical trials, focusing on statistical analysis, data management, and regulatory submissions.',
  //   subtopic: 'Clinical Data Management and Analysis',
  // },
  // {
  //   id: 71,
  //   title: 'Clinical Trials and Research',
  //   slug: 'clinical-sas-c71',
  //   price: 170.0,
  //   image: '/images/vision/clinical-trial-research.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Science',
  //   priority: 5,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Gain expertise in clinical trials and research methodologies, focusing on data collection, analysis, and regulatory compliance.',
  //   subtopic: 'Clinical Data Management and Analysis',
  // },
  {
    id: 72,
    title: 'Artificial Intelligence & Machine Learning',
    slug: 'ai-c72',
    price: 200.0,
    image: '/images/vision/artificial-intelligence.webp',
    program: 'Degree',
    branch: 'Bachelor of Science',
    priority: 6,
    reviews: 16,
    rating: 5,
    description:
      'Learn the fundamentals of AI, machine learning, and deep learning applications in various fields like healthcare, business, and robotics.',
    subtopic: 'AI and Machine Learning Applications',
  },
  // {
  //   id: 73,
  //   title: 'Drug Development',
  //   slug: 'drug-development-c73',
  //   price: 210.0,
  //   image: '/images/degree/drug.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Science',
  //   priority: 7,
  //   reviews: 12,
  //   rating: 5,
  //   description:
  //     'Explore the stages of drug development, from discovery and preclinical testing to clinical trials and regulatory approval.',
  //   subtopic: 'Pharmaceutical Drug Development Process',
  // },
  // {
  //   id: 74,
  //   title: 'Regulatory Affairs',
  //   slug: 'regulatory-affairs-c74',
  //   price: 160.0,
  //   image: '/images/degree/regular.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Science',
  //   priority: 8,
  //   reviews: 14,
  //   rating: 4,
  //   description:
  //     'Gain knowledge of the regulatory environment in the pharmaceutical and healthcare industries, focusing on international compliance standards.',
  //   subtopic: 'Regulation and Compliance in Pharma',
  // },

  {
    id: 78,
    title: 'Business Analytics',
    slug: 'business-analytics-c78',
    price: 210.0,
    image: '/images/degree/business.webp',
    program: 'Degree',
    branch: 'Bachelor of Business Administration',
    priority: 4,
    reviews: 14,
    rating: 5,
    description:
      'Understand how to use data analysis and business intelligence tools to support decision-making and improve business operations.',
    subtopic: 'Data Analysis and Business Intelligence',
  },
  // {
  //   id: 79,
  //   title: 'Blockchain',
  //   slug: 'blockchain-c79',
  //   price: 220.0,
  //   image: '/images/degree/blockchain.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 5,
  //   reviews: 12,
  //   rating: 5,
  //   description:
  //     'Study the fundamentals of blockchain technology, including its applications in finance, security, and business operations.',
  //   subtopic: 'Blockchain Technology and Applications',
  // },
  // {
  //   id: 80,
  //   title: 'Product Management',
  //   slug: 'product-management-c80',
  //   price: 250.0,
  //   image: '/images/degree/product.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 6,
  //   reviews: 16,
  //   rating: 4,
  //   description:
  //     'Learn how to manage the lifecycle of a product, from concept to launch, with a focus on market research, development, and product strategy.',
  //   subtopic: 'Product Development and Strategy',
  // },
  // {
  //   id: 81,
  //   title: 'Supply Chain Management',
  //   slug: 'supply-chain-management-c81',
  //   price: 240.0,
  //   image: '/images/degree/supply.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 7,
  //   reviews: 14,
  //   rating: 5,
  //   description:
  //     'Explore the key concepts in managing supply chains, including logistics, procurement, and inventory management.',
  //   subtopic: 'Logistics and Supply Chain Optimization',
  // },
  // {
  //   id: 82,
  //   title: 'Operations Management',
  //   slug: 'operations-management-c82',
  //   price: 230.0,
  //   image: '/images/degree/operation.webp',
  //   program: 'Degree',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 8,
  //   reviews: 12,
  //   rating: 4,
  //   description:
  //     'Understand the core principles of managing business operations, including production, quality control, and process improvement.',
  //   subtopic: 'Business Operations and Process Improvement',
  // },
  {
    id: 83,
    title: 'Human Resource ',
    slug: 'hr-c83',
    price: 180.0,
    image: '/images/degree/hr.webp',
    program: 'MBA',
    branch: 'Bachelor of Business Administration',
    priority: 1,
    reviews: 18,
    rating: 4,
    description:
      'Study the practices and principles of managing a company’s workforce, including recruitment, employee relations, and performance management.',
    subtopic: 'Employee Management and Development',
  },

  {
    id: 85,
    title: 'Digital Marketing',
    slug: 'digital-marketing-c85',
    price: 200.0,
    image: '/images/btech/mba/digital.webp',
    program: 'MBA',
    branch: 'Bachelor of Business Administration',
    priority: 3,
    reviews: 15,
    rating: 5,
    description:
      'Gain expertise in digital marketing strategies, including SEO, content marketing, social media, and email campaigns.',
    subtopic: 'Digital Marketing Strategies',
  },
  // {
  //   id: 84,
  //   title: 'Finance',
  //   slug: 'finance-c84',
  //   price: 190.0,
  //   image: '/images/btech/mba/finance.webp',
  //   program: 'MBA',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 2,
  //   reviews: 22,
  //   rating: 5,
  //   description:
  //     'Learn the principles of financial management, including investment strategies, accounting, and financial analysis.',
  //   subtopic: 'Financial Management and Analysis',
  // },
  {
    id: 86,
    title: 'Business Analytics',
    slug: 'business-analytics-c86',
    price: 210.0,
    image: '/images/btech/mba/business.webp',
    program: 'MBA',
    branch: 'Bachelor of Business Administration',
    priority: 4,
    reviews: 14,
    rating: 5,
    description:
      'Understand how to use data analysis and business intelligence tools to support decision-making and improve business operations.',
    subtopic: 'Data Analysis and Business Intelligence',
  },
  // {
  //   id: 87,
  //   title: 'Blockchain',
  //   slug: 'blockchain-c87',
  //   price: 220.0,
  //   image: '/images/btech/mba/blockchain.webp',
  //   program: 'MBA',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 5,
  //   reviews: 12,
  //   rating: 5,
  //   description:
  //     'Study the fundamentals of blockchain technology, including its applications in finance, security, and business operations.',
  //   subtopic: 'Blockchain Technology and Applications',
  // },
  // {
  //   id: 88,
  //   title: 'Product Management',
  //   slug: 'product-management-c88',
  //   price: 250.0,
  //   image: '/images/btech/mba/product.webp',
  //   program: 'MBA',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 6,
  //   reviews: 16,
  //   rating: 4,
  //   description:
  //     'Learn how to manage the lifecycle of a product, from concept to launch, with a focus on market research, development, and product strategy.',
  //   subtopic: 'Product Development and Strategy',
  // },
  // {
  //   id: 89,
  //   title: 'Supply Chain Management',
  //   slug: 'supply-chain-management-c89',
  //   price: 240.0,
  //   image: '/images/btech/mba/supply.webp',
  //   program: 'MBA',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 7,
  //   reviews: 14,
  //   rating: 5,
  //   description:
  //     'Explore the key concepts in managing supply chains, including logistics, procurement, and inventory management.',
  //   subtopic: 'Logistics and Supply Chain Optimization',
  // },
  // {
  //   id: 90,
  //   title: 'Operations Management',
  //   slug: 'operations-management-c90',
  //   price: 230.0,
  //   image: '/images/btech/mba/operation.webp',
  //   program: 'MBA',
  //   branch: 'Bachelor of Business Administration',
  //   priority: 8,
  //   reviews: 12,
  //   rating: 4,
  //   description:
  //     'Understand the core principles of managing business operations, including production, quality control, and process improvement.',
  //   subtopic: 'Business Operations and Process Improvement',
  // },
  {
    id: 91,
    title: 'Artificial Intelligence & Machine Learning',
    slug: 'ai-c91',
    price: 450.0,
    image: '/images/vision/artificial-intelligence.webp',
    program: 'MCA',
    branch: 'Master of Computer Applications',
    priority: 1,
    reviews: 28,
    rating: 5,
    description:
      'Learn the principles of AI, machine learning, deep learning, and their applications in various industries.',
    subtopic: 'AI Algorithms and Applications',
  },
  // {
  //   id: 92,
  //   title: 'Machine Learning',
  //   slug: 'ml-c92',
  //   price: 470.0,
  //   image: '/images/vision/machine-learning.jpg',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 2,
  //   reviews: 30,
  //   rating: 5,
  //   description:
  //     'Study machine learning algorithms and techniques to solve complex data-driven problems and make predictive models.',
  //   subtopic: 'ML Algorithms and Predictive Modeling',
  // },
  // {
  //   id: 93,
  //   title: 'Data Science',
  //   slug: 'data-science-c93',
  //   price: 480.0,
  //   image: '/images/degree/ds.avif',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 3,
  //   reviews: 25,
  //   rating: 5,
  //   description:
  //     'Learn to analyze, visualize, and interpret large datasets, using data science tools like Python, R, and SQL.',
  //   subtopic: 'Data Analysis and Visualization',
  // },
  {
    id: 94,
    title: 'Full Stack Web Developement',
    slug: 'full-stack-web-development-c94',
    price: 500.0,
    image: '/images/vision/fullstack.webp',
    program: 'MCA',
    branch: 'Master of Computer Applications',
    priority: 4,
    reviews: 22,
    rating: 5,
    description:
      'Become proficient in both front-end and back-end web development, including HTML, CSS, JavaScript, and databases.',
    subtopic: 'Web Development and Programming',
  },
  {
    id: 95,
    title: 'QA Testing and Automation',
    slug: 'qa-testing-c95',
    price: 460.0,
    image: '/images/degree/qa.webp',
    program: 'MCA',
    branch: 'Master of Computer Applications',
    priority: 5,
    reviews: 18,
    rating: 4,
    description:
      'Learn quality assurance techniques for testing software, applications, and systems for functionality, security, and performance.',
    subtopic: 'Software Testing and Quality Assurance',
  },
  // {
  //   id: 96,
  //   title: 'Power BI',
  //   slug: 'power-bi-c96',
  //   price: 440.0,
  //   image: '/images/vision/powerbi.webp',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 6,
  //   reviews: 20,
  //   rating: 5,
  //   description:
  //     'Master Power BI to create business intelligence reports and dashboards that enable data-driven decision-making.',
  //   subtopic: 'Business Intelligence and Data Reporting',
  // },
  // {
  //   id: 97,
  //   title: 'Cloud Computing',
  //   slug: 'cloud-computing-c97',
  //   price: 470.0,
  //   image: '/images/vision/cloud-computing.webp',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 7,
  //   reviews: 22,
  //   rating: 5,
  //   description:
  //     'Understand cloud computing technologies, cloud service models, and their applications in the modern IT landscape.',
  //   subtopic: 'Cloud Infrastructure and Services',
  // },
  // {
  //   id: 98,
  //   title: 'Cyber Security',
  //   slug: 'cyber-security-c98',
  //   price: 480.0,
  //   image: '/images/degree/cyber.webp',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 8,
  //   reviews: 15,
  //   rating: 4,
  //   description:
  //     'Learn to protect networks, data, and systems from cyber-attacks, focusing on ethical hacking and security protocols.',
  //   subtopic: 'Network and Information Security',
  // },
  // {
  //   id: 99,
  //   title: 'Mobile App Development',
  //   slug: 'mobile-app-development-c99',
  //   price: 450.0,
  //   image: '/images/vision/mobile-development.webp',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 9,
  //   reviews: 18,
  //   rating: 5,
  //   description:
  //     'Learn how to design and develop mobile applications for iOS and Android using modern frameworks and programming languages.',
  //   subtopic: 'Mobile Development and Programming',
  // },
  // {
  //   id: 100,
  //   title: 'DevOps',
  //   slug: 'devops-c100',
  //   price: 460.0,
  //   image: '/images/vision/devops.webp',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 10,
  //   reviews: 20,
  //   rating: 5,
  //   description:
  //     'Explore DevOps principles, focusing on automation, continuous integration, and deployment pipelines in software development.',
  //   subtopic: 'Automation and Software Deployment',
  // },
  // {
  //   id: 101,
  //   title: 'Robotics',
  //   slug: 'robotics-c101',
  //   price: 490.0,
  //   image: '/images/vision/robotics.webp',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 11,
  //   reviews: 18,
  //   rating: 5,
  //   description:
  //     'Understand the fundamentals of robotics, including robotic design, control systems, and automation technologies.',
  //   subtopic: 'Robotics Engineering and Automation',
  // },
  // {
  //   id: 102,
  //   title: 'AR/VR Development',
  //   slug: 'ar-vr-c102',
  //   price: 500.0,
  //   image: '/images/vision/augemented.webp',
  //   program: 'MCA',
  //   branch: 'Master of Computer Applications',
  //   priority: 12,
  //   reviews: 22,
  //   rating: 5,
  //   description:
  //     'Learn to develop augmented reality (AR) and virtual reality (VR) applications, integrating interactive experiences with hardware.',
  //   subtopic: 'AR/VR Development and Applications',
  // },
  {
    id: 103,
    title: 'Artificial Intelligence & Machine Learning',
    slug: 'ai-c103',
    price: 400.0,
    image: '/images/vision/artificial-intelligence.webp',
    program: 'Agriculture',
    branch: 'Agriculture',
    priority: 1,
    reviews: 25,
    rating: 5,
    description:
      'Explore the application of AI in agriculture for crop management, precision farming, and improving yield prediction.',
    subtopic: 'AI in Precision Farming',
  },
  {
    id: 104,
    title: 'Nano Science and Nano Technology',
    slug: 'nano-science-c104',
    price: 420.0,
    image: '/images/btech/agriculture/nano.webp',
    program: 'Agriculture',
    branch: 'Agriculture',
    priority: 2,
    reviews: 22,
    rating: 5,
    description:
      'Learn how nanotechnology can improve agricultural processes such as pest control, soil quality, and crop productivity.',
    subtopic: 'Nanotechnology for Sustainable Agriculture',
  },
  // {
  //   id: 105,
  //   title: 'Research and Development',
  //   slug: 'research-development-c105',
  //   price: 450.0,
  //   image: '/images/btech/agriculture/research.webp',
  //   program: 'Agriculture',
  //   branch: 'Agriculture',
  //   priority: 3,
  //   reviews: 18,
  //   rating: 4,
  //   description:
  //     'Understand the critical role of R&D in advancing agricultural practices, focusing on sustainable farming techniques and new innovations.',
  //   subtopic: 'Agricultural Research and Innovation',
  // },
  {
    id: 106,
    title: 'Genetic Engineering',
    slug: 'genetics-c106',
    price: 470.0,
    image: '/images/btech/agriculture/genetics.webp',
    program: 'Agriculture',
    branch: 'Agriculture',
    priority: 4,
    reviews: 30,
    rating: 5,
    description:
      'Study how genetic principles are applied in agriculture to improve crops, resistance to diseases, and overall food production.',
    subtopic: 'Genetics and Crop Improvement',
  },
  // {
  //   id: 107,
  //   title: 'AutoCAD',
  //   slug: 'autocad-c107',
  //   price: 140.0,
  //   image: '/images/btech/mechanical/autocad.webp',
  //   program: 'B.Tech',
  //   branch: 'Mechanical Engineering',
  //   priority: 1,
  //   reviews: 15,
  //   rating: 5,
  //   description:
  //     'Learn how to use AutoCAD for designing automotive parts and creating 2D and 3D models for vehicle components.',
  //   subtopic: 'Vehicle Component Design and Drafting',
  // },
  {
    id: 108,
    title: 'Hybrid and Electric Vehicles',
    slug: 'hybrid-and-electric-vehicles-c108',
    price: 180.0,
    image: '/images/btech/mechanical/hybrid.webp',
    program: 'B.Tech',
    branch: 'Mechanical Engineering',
    priority: 2,
    reviews: 10,
    rating: 4,
    description:
      'Study the principles behind hybrid and electric vehicles, including power systems, battery technology, and charging infrastructure.',
    subtopic: 'Electric Drive Systems and Battery Management',
  },
  {
    id: 109,
    title: 'Internal Combustion Engine',
    slug: 'internal-combustion-engine-c109',
    price: 160.0,
    image: '/images/btech/mechanical/internal.webp',
    program: 'B.Tech',
    branch: 'Mechanical Engineering',
    priority: 3,
    reviews: 12,
    rating: 4,
    description:
      'Understand the workings of internal combustion engines, including fuel systems, thermodynamics, and engine performance.',
    subtopic: 'Engine Components and Thermodynamics',
  },
  {
    id: 110,
    title: 'Car Designing',
    slug: 'car-designing-c110',
    price: 200.0,
    image: '/images/btech/mechanical/cardesign.webp',
    program: 'B.Tech',
    branch: 'Mechanical Engineering',
    priority: 4,
    reviews: 18,
    rating: 5,
    description:
      'Learn the design and manufacturing process of a car, from conceptualization to production, focusing on vehicle architecture and styling.',
    subtopic: 'Vehicle Design, CAD Modeling, and Production',
  },
  // {
  //   id: 111,
  //   title: 'Embedded Systems Design',
  //   slug: 'embedded-systems-design-c111',
  //   price: 150.0,
  //   image: '/images/btech/ee/embedded.webp',
  //   program: 'B.Tech',
  //   branch: 'Electrical Engineering',
  //   priority: 1,
  //   reviews: 14,
  //   rating: 5,
  //   description:
  //     'Learn how to design and develop embedded systems for applications in automation, control, and IoT.',
  //   subtopic: 'Microcontrollers and Embedded Programming',
  // },
  {
    id: 112,
    title: 'Control Systems',
    slug: 'control-systems-c112',
    price: 170.0,
    image: '/images/btech/ee/control.webp',
    program: 'B.Tech',
    branch: 'Electrical Engineering',
    priority: 2,
    reviews: 16,
    rating: 4,
    description:
      'Study the analysis, design, and implementation of control systems used in industrial and automotive applications.',
    subtopic: 'Feedback Control and System Stability',
  },
  {
    id: 113,
    title: 'Renewable Energy Systems',
    slug: 'renewable-energy-systems-c113',
    price: 180.0,
    image: '/images/btech/ee/renewable.webp',
    program: 'B.Tech',
    branch: 'Electrical Engineering',
    priority: 3,
    reviews: 10,
    rating: 5,
    description:
      'Understand the principles and technologies behind renewable energy sources like solar, wind, and geothermal power.',
    subtopic: 'Solar Power, Wind Energy, and Storage Systems',
  },
  {
    id: 114,
    title: 'Power Electronics',
    slug: 'power-electronics-c114',
    price: 160.0,
    image: '/images/btech/ee/electronics.webp',
    program: 'B.Tech',
    branch: 'Electrical Engineering',
    priority: 4,
    reviews: 12,
    rating: 4,
    description:
      'Learn the principles and applications of power electronic devices used in energy conversion, motor drives, and power supplies.',
    subtopic: 'Power Converters and Motor Drives',
  },
  // {
  //   id: 115,
  //   title: 'AutoCAD',
  //   slug: 'autocad-c115',
  //   price: 140.0,
  //   image: '/images/btech/automobile/autocad.webp',
  //   program: 'B.Tech',
  //   branch: 'Automobile Engineering',
  //   priority: 1,
  //   reviews: 15,
  //   rating: 5,
  //   description:
  //     'Learn how to use AutoCAD for designing automotive parts and creating 2D and 3D models for vehicle components.',
  //   subtopic: 'Vehicle Component Design and Drafting',
  // },
  {
    id: 116,
    title: 'Hybrid and Electric Vehicles',
    slug: 'hybrid-and-electric-vehicles-c116',
    price: 180.0,
    image: '/images/btech/automobile/hybrid.webp',
    program: 'B.Tech',
    branch: 'Automobile Engineering',
    priority: 2,
    reviews: 10,
    rating: 4,
    description:
      'Study the principles behind hybrid and electric vehicles, including power systems, battery technology, and charging infrastructure.',
    subtopic: 'Electric Drive Systems and Battery Management',
  },
  {
    id: 117,
    title: 'Internal Combustion Engine',
    slug: 'internal-combustion-engine-c117',
    price: 160.0,
    image: '/images/btech/automobile/internal.webp',
    program: 'B.Tech',
    branch: 'Automobile Engineering',
    priority: 3,
    reviews: 12,
    rating: 4,
    description:
      'Understand the workings of internal combustion engines, including fuel systems, thermodynamics, and engine performance.',
    subtopic: 'Engine Components and Thermodynamics',
  },
  {
    id: 118,
    title: 'Car Designing',
    slug: 'car-designing-c118',
    price: 200.0,
    image: '/images/btech/automobile/cardesign.webp',
    program: 'B.Tech',
    branch: 'Automobile Engineering',
    priority: 4,
    reviews: 18,
    rating: 5,
    description:
      'Learn the design and manufacturing process of a car, from conceptualization to production, focusing on vehicle architecture and styling.',
    subtopic: 'Vehicle Design, CAD Modeling, and Production',
  },
  {
    id: 119,
    title: 'Human Resource',
    slug: 'human-resource-management-c119',
    price: 350.0,
    image: '/images/btech/mba/hr.webp',
    program: 'MBA',
    branch: 'Master of Business Administration',
    priority: 1,
    reviews: 25,
    rating: 5,
    description:
      'Study advanced HR practices including strategic workforce planning, talent management, and organizational behavior.',
    subtopic: 'HR Strategy and Management',
  },
  // {
  //   id: 120,
  //   title: 'Finance',
  //   slug: 'finance-c120',
  //   price: 400.0,
  //   image: '/images/btech/mba/finance.webp',
  //   program: 'MBA',
  //   branch: 'Master of Business Administration',
  //   priority: 2,
  //   reviews: 28,
  //   rating: 5,
  //   description:
  //     'Learn advanced financial management, investment strategies, corporate finance, and financial modeling.',
  //   subtopic: 'Corporate Finance and Investment Analysis',
  // },
  {
    id: 121,
    title: 'Digital Marketing',
    slug: 'digital-marketing-c121',
    price: 380.0,
    image: '/images/btech/mba/digital.webp',
    program: 'MBA',
    branch: 'Master of Business Administration',
    priority: 3,
    reviews: 22,
    rating: 5,
    description:
      'Master the tools and techniques of digital marketing, including SEO, social media marketing, email campaigns, and data analytics.',
    subtopic: 'Digital Marketing and Strategy',
  },
  {
    id: 122,
    title: 'Business Analytics',
    slug: 'business-analytics-c122',
    price: 420.0,
    image: '/images/btech/mba/business.webp',
    program: 'MBA',
    branch: 'Master of Business Administration',
    priority: 4,
    reviews: 20,
    rating: 5,
    description:
      'Understand how to leverage data analytics to inform business decisions, using tools like Excel, Tableau, and Power BI.',
    subtopic: 'Data Analytics for Business Decisions',
  },
  {
    id: 123,
    title: 'Blockchain',
    slug: 'blockchain-c123',
    price: 450.0,
    image: '/images/btech/mba/blockchain.webp',
    program: 'MBA',
    branch: 'Master of Business Administration',
    priority: 5,
    reviews: 18,
    rating: 5,
    description:
      'Study blockchain technology and its applications in finance, supply chain management, and business operations.',
    subtopic: 'Blockchain and Distributed Ledger Technology',
  },
  {
    id: 124,
    title: 'Product Management',
    slug: 'product-management-c124',
    price: 470.0,
    image: '/images/btech/mba/product.webp',
    program: 'MBA',
    branch: 'Master of Business Administration',
    priority: 6,
    reviews: 24,
    rating: 5,
    description:
      'Learn how to develop and manage products from ideation to market launch, with an emphasis on strategy, design, and customer experience.',
    subtopic: 'Product Strategy and Management',
  },
  {
    id: 125,
    title: 'Supply Chain Management',
    slug: 'supply-chain-management-c125',
    price: 460.0,
    image: '/images/btech/mba/supply.webp',
    program: 'MBA',
    branch: 'Master of Business Administration',
    priority: 7,
    reviews: 15,
    rating: 5,
    description:
      'Gain expertise in supply chain strategy, logistics, procurement, and the integration of technology to optimize operations.',
    subtopic: 'Logistics and Supply Chain Strategy',
  },
  {
    id: 126,
    title: 'Operations Management',
    slug: 'operations-management-c126',
    price: 440.0,
    image: '/images/btech/mba/operation.webp',
    program: 'MBA',
    branch: 'Master of Business Administration',
    priority: 8,
    reviews: 20,
    rating: 4,
    description:
      'Study advanced operations management concepts such as process optimization, capacity planning, and lean manufacturing.',
    subtopic: 'Operational Excellence and Process Improvement',
  },
];
